# Generated by Django 5.2.4 on 2025-07-19 19:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(max_length=200)),
                ('car', models.CharField(max_length=200)),
                ('session_type', models.CharField(max_length=50)),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_name', models.CharField(max_length=255)),
                ('players_data', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='Lap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lap_number', models.IntegerField()),
                ('driver_name', models.CharField(max_length=200)),
                ('car_index', models.IntegerField()),
                ('total_time', models.FloatField()),
                ('sector1_time', models.FloatField()),
                ('sector2_time', models.FloatField()),
                ('sector3_time', models.FloatField()),
                ('tyre_compound', models.CharField(max_length=50)),
                ('cuts', models.IntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laps', to='laptimes.session')),
            ],
            options={
                'ordering': ['session', 'lap_number'],
                'unique_together': {('session', 'lap_number', 'car_index')},
            },
        ),
    ]
