# Generated by Django 5.2.4 on 2025-09-01 23:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Car name as imported from JSON files",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable car name for display",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_name", "code"],
                "indexes": [
                    models.Index(fields=["code"], name="laptimes_ca_code_e3cf70_idx"),
                    models.Index(
                        fields=["display_name"], name="laptimes_ca_display_0fe0c2_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Track name as imported from JSON files",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable track name for display",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_name", "code"],
                "indexes": [
                    models.Index(fields=["code"], name="laptimes_tr_code_ba8390_idx"),
                    models.Index(
                        fields=["display_name"], name="laptimes_tr_display_7c0bce_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_name", models.CharField(blank=True, max_length=200)),
                ("session_type", models.CharField(max_length=50)),
                (
                    "upload_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("players_data", models.JSONField(default=dict)),
                (
                    "file_hash",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("fastest_lap_time", models.FloatField(blank=True, null=True)),
                ("fastest_lap_driver", models.CharField(blank=True, max_length=200)),
                ("total_laps", models.IntegerField(default=0)),
                ("total_drivers", models.IntegerField(default=0)),
                ("session_statistics", models.JSONField(default=dict)),
                ("chart_data", models.JSONField(default=dict)),
                ("sector_statistics", models.JSONField(default=dict)),
                ("last_calculated", models.DateTimeField(auto_now=True)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="laptimes.car",
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="laptimes.track",
                    ),
                ),
            ],
            options={
                "ordering": ["-upload_date"],
            },
        ),
        migrations.CreateModel(
            name="Lap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lap_number", models.IntegerField()),
                ("driver_name", models.CharField(max_length=200)),
                ("car_index", models.IntegerField()),
                ("total_time", models.FloatField()),
                ("sectors", models.JSONField(default=list)),
                ("tyre_compound", models.CharField(max_length=50)),
                ("cuts", models.IntegerField(default=0)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="laps",
                        to="laptimes.session",
                    ),
                ),
            ],
            options={
                "ordering": ["session", "lap_number"],
                "unique_together": {("session", "lap_number", "car_index")},
            },
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["file_hash"], name="laptimes_se_file_ha_a64e36_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["-upload_date"], name="laptimes_se_upload__c9593b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(fields=["track"], name="laptimes_se_track_i_8f466c_idx"),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(fields=["car"], name="laptimes_se_car_id_8fc82d_idx"),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["session_type"], name="laptimes_se_session_5f37ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["track", "-upload_date"], name="laptimes_se_track_i_044548_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["car", "-upload_date"], name="laptimes_se_car_id_73f51e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["session_type", "-upload_date"],
                name="laptimes_se_session_c175be_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["last_calculated"], name="laptimes_se_last_ca_588d2f_idx"
            ),
        ),
    ]
