# Generated by Django 5.2.4 on 2025-07-23 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptimes', '0003_lap_sectors_jsonfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['file_hash'], name='laptimes_se_file_ha_a64e36_idx'),
        ),
    ]
