# Generated by Django 5.2.4 on 2025-07-27 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laptimes", "0004_session_file_hash_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["-upload_date"], name="laptimes_se_upload__c9593b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(fields=["track"], name="laptimes_se_track_f59599_idx"),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(fields=["car"], name="laptimes_se_car_02fd4d_idx"),
        ),
    ]
