# Generated by Django 5.2.4 on 2025-07-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laptimes", "0005_session_laptimes_se_upload__c9593b_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["session_type"], name="laptimes_se_session_5f37ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["track", "-upload_date"], name="laptimes_se_track_812bc7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["car", "-upload_date"], name="laptimes_se_car_994d90_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["session_type", "-upload_date"],
                name="laptimes_se_session_c175be_idx",
            ),
        ),
    ]
