# Generated by Django 5.2.4 on 2025-09-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laptimes", "0006_session_laptimes_se_session_5f37ac_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="chart_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="session",
            name="fastest_lap_driver",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="session",
            name="fastest_lap_time",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="last_calculated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="session",
            name="sector_statistics",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="session",
            name="session_statistics",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="session",
            name="total_drivers",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="session",
            name="total_laps",
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["last_calculated"], name="laptimes_se_last_ca_588d2f_idx"
            ),
        ),
    ]
