name: PR Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Django system checks
      run: |
        python manage.py check

    - name: Check for migration issues
      run: |
        python manage.py makemigrations --check --dry-run

    - name: Run database migrations
      run: |
        python manage.py migrate

    - name: Run all tests
      run: |
        python manage.py test --verbosity=2

    - name: Test count verification
      run: |
        echo "Verifying test count..."
        TEST_COUNT=$(python manage.py test --verbosity=0 2>&1 | grep -o "Ran [0-9]* test" | grep -o "[0-9]*")
        echo "Total tests run: $TEST_COUNT"
        if [ "$TEST_COUNT" -lt 50 ]; then
          echo "Warning: Expected at least 50 tests, but only $TEST_COUNT were run"
          exit 1
        fi
        echo "✅ Test count verification passed: $TEST_COUNT tests"

    - name: Run duplicate file prevention tests specifically
      run: |
        echo "Testing duplicate file prevention functionality..."
        python manage.py test laptimes.tests.DuplicateFileTests --verbosity=2
        python manage.py test laptimes.tests.AdminInterfaceTests --verbosity=2